package engine

import (
	"io"
	"os"
	"path/filepath"
	"strings"
)

// copyNucleiResumeCfg looks for a resume file generated by nuclei in the
// default ~/.config/nuclei/ directory and copies it to the artifacts directory.
func copyNucleiResumeCfg(logPath, artDir string) string {
	// Parse nuclei log for the resume file path if available
	cfgPath := ""
	if b, err := os.ReadFile(logPath); err == nil {
		for _, line := range strings.Split(string(b), "\n") {
			if strings.Contains(line, "Creating resume file:") {
				parts := strings.SplitN(line, "Creating resume file:", 2)
				if len(parts) == 2 {
					cfgPath = strings.TrimSpace(parts[1])
					break
				}
			}
		}
	}

	// Fallback to checking ~/.config/nuclei directly for recent files
	if cfgPath == "" {
		homeDir, err := os.UserHomeDir()
		if err == nil {
			nucleiConfigDir := filepath.Join(homeDir, ".config", "nuclei")
			if entries, err := os.ReadDir(nucleiConfigDir); err == nil {
				var latestCfg string
				var latestTime int64
				for _, entry := range entries {
					if !entry.IsDir() && strings.HasPrefix(entry.Name(), "resume") && strings.HasSuffix(entry.Name(), ".cfg") {
						info, err := entry.Info()
						if err == nil && info.ModTime().UnixNano() > latestTime {
							latestTime = info.ModTime().UnixNano()
							latestCfg = filepath.Join(nucleiConfigDir, entry.Name())
						}
					}
				}
				cfgPath = latestCfg
			}
		}
	}

	if cfgPath == "" {
		return ""
	}

	// Copy to artDir
	destPath := filepath.Join(artDir, filepath.Base(cfgPath))
	src, err := os.Open(cfgPath)
	if err != nil {
		return ""
	}
	defer src.Close()

	dst, err := os.Create(destPath)
	if err != nil {
		return ""
	}
	defer dst.Close()

	if _, err := io.Copy(dst, src); err != nil {
		return ""
	}

	return destPath
}

// fileExists checks if a file exists and is not a directory
func fileExists(filename string) bool {
info, err := os.Stat(filename)
if os.IsNotExist(err) {
return false
}
return !info.IsDir()
}
